import { supabaseAdmin } from '@/lib/supabase/admin'
import type { Survey } from '@/lib/types/survey'

// Untyped admin client — Database schema is a stub; real types generated by Supabase CLI in Phase 3
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const db = supabaseAdmin as any

interface PageProps {
  params: Promise<{ id: string }>
}

export default async function PublicConfirmationPage({ params }: PageProps) {
  const { id: surveyId } = await params

  // Fetch survey title for display
  const { data: surveyData } = await db
    .from('surveys')
    .select('title, description')
    .eq('id', surveyId)
    .single()

  const survey = surveyData as Pick<Survey, 'title' | 'description'> | null

  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center p-8">
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8 max-w-md w-full text-center">
        {/* Success icon */}
        <div className="w-16 h-16 mx-auto mb-6 rounded-full bg-green-100 flex items-center justify-center">
          <svg
            className="w-8 h-8 text-green-600"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M5 13l4 4L19 7"
            />
          </svg>
        </div>

        <h1 className="text-2xl font-semibold text-gray-900 mb-2">Thank you for your response!</h1>

        {survey?.title && (
          <p className="text-gray-500 mb-4">{survey.title}</p>
        )}

        <p className="text-sm text-gray-600 mb-6">
          Your response has been recorded anonymously. Leadership reviews all submissions
          to build a better workplace.
        </p>

        <p className="text-xs text-gray-400">
          You may close this page. Your submission is complete.
        </p>
      </div>
    </div>
  )
}
