'use server'
import { supabaseAdmin } from '@/lib/supabase/admin'
import { cookies } from 'next/headers'

// Untyped admin client — Database schema is a stub; real types generated by Supabase CLI in Phase 3
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const db = supabaseAdmin as any

/**
 * Submit a public (unauthenticated) survey response.
 *
 * - No auth context available — uses supabaseAdmin for all DB writes
 * - No participation_token created (no user_id to store)
 * - Cookie-based soft deduplication: survey_submitted_<surveyId>
 * - Response row: user_id=NULL, is_anonymous=true, segmentation metadata all NULL
 * - Does NOT increment any public_response_count — participation rate tracking deferred to Phase 3
 */
export async function submitPublicResponse(
  surveyId: string,
  answers: Record<string, unknown>
): Promise<{ success: true } | { success: false; error: string }> {
  // (1) Validate surveyId
  if (!surveyId || typeof surveyId !== 'string' || surveyId.trim() === '') {
    return { success: false, error: 'Invalid survey ID' }
  }

  // (2) Verify survey exists, is public, and is open
  const { data: survey, error: surveyError } = await db
    .from('surveys')
    .select('id, status, public_link_enabled')
    .eq('id', surveyId)
    .single()

  if (surveyError || !survey) {
    return { success: false, error: 'Survey is not available' }
  }

  const s = survey as { id: string; status: string; public_link_enabled: boolean }
  if (!s.public_link_enabled || s.status !== 'open') {
    return { success: false, error: 'Survey is not available' }
  }

  // (3) Check cookie for duplicate submission
  const cookieStore = await cookies()
  const cookieName = `survey_submitted_${surveyId}`
  const existingCookie = cookieStore.get(cookieName)
  if (existingCookie) {
    return { success: false, error: 'already_submitted' }
  }

  // (4) Insert response row — user_id=NULL, is_anonymous=true, segmentation all NULL
  const { data: responseData, error: responseError } = await db
    .from('responses')
    .insert({
      survey_id: surveyId,
      user_id: null,
      is_anonymous: true,
      submitted_at: new Date().toISOString(),
      department: null,
      role: null,
      tenure_band: null,
      work_type: null,
    })
    .select()
    .single()

  if (responseError) return { success: false, error: responseError.message }

  const responseId = (responseData as { id: string }).id

  // (5) Insert response_answers rows
  const answerRows = Object.entries(answers).map(([question_id, value]) => ({
    response_id: responseId,
    question_id,
    answer_text: typeof value === 'string' ? value : null,
    answer_numeric: typeof value === 'number' ? value : null,
    answer_options: Array.isArray(value) ? value : null,
  }))

  if (answerRows.length > 0) {
    const { error: answersError } = await db.from('response_answers').insert(answerRows)
    if (answersError) return { success: false, error: answersError.message }
  }

  // (6) Set deduplication cookie (1 year, httpOnly, lax)
  cookieStore.set(cookieName, '1', {
    maxAge: 60 * 60 * 24 * 365,
    path: '/',
    httpOnly: true,
    sameSite: 'lax',
  })

  return { success: true }
}
