'use server'
import { revalidatePath } from 'next/cache'
import { createSupabaseServerClient } from '@/lib/supabase/server'
import { supabaseAdmin } from '@/lib/supabase/admin'
import {
  saveDraftSchema,
  submitResponseSchema,
} from '@/lib/validations/survey'
import {
  buildLegacyDraftPayload,
  buildModernDraftPayload,
  getSurveyAnonymousFlag,
  mapAnswerValueForStorage,
  normalizeDraftRow,
  shouldRetryWithLegacyDraftColumns,
  shouldRetryWithLegacySurveyColumns,
} from './response-draft-compat'
import { getMissingColumnName } from './survey-compat'
import type {
  ResponseDraft,
  SurveyResponse,
  SubmissionStatus,
} from '@/lib/types/survey'

// Untyped admin client — Database schema is a stub; real types generated by Supabase CLI in Phase 3
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const db = supabaseAdmin as any

type IdRow = { id: string }
type SurveyStatusRow = { status: string | null }
type AudienceRoleRow = { target_role_id: string | null }
type ParticipationUserRow = { user_id: string | null }

async function autoCloseSurveyIfCompleted(surveyId: string): Promise<void> {
  const { data: surveyData, error: surveyError } = await db
    .from('surveys')
    .select('status')
    .eq('id', surveyId)
    .maybeSingle()

  if (surveyError) return
  const survey = surveyData as SurveyStatusRow | null
  if (!survey || survey.status !== 'open') return

  const { data: audienceData, error: audienceError } = await db
    .from('survey_audiences')
    .select('target_role_id')
    .eq('survey_id', surveyId)
    .not('target_role_id', 'is', null)

  if (audienceError) return

  const targetRoleIds = (((audienceData as AudienceRoleRow[] | null) ?? [])
    .map((row) => row.target_role_id)
    .filter((id): id is string => typeof id === 'string' && id.length > 0))

  let eligibleQuery = db
    .from('profiles')
    .select('id')
    .eq('is_active', true)

  if (targetRoleIds.length > 0) {
    eligibleQuery = eligibleQuery.in('role_id', targetRoleIds)
  }

  const { data: eligibleRows, error: eligibleError } = await eligibleQuery
  if (eligibleError) return

  const eligibleUserIds = (((eligibleRows as IdRow[] | null) ?? [])
    .map((row) => row.id)
    .filter((id) => typeof id === 'string' && id.length > 0))

  if (eligibleUserIds.length === 0) return

  const { data: submittedData, error: submittedError } = await db
    .from('participation_tokens')
    .select('user_id')
    .eq('survey_id', surveyId)
    .in('user_id', eligibleUserIds)

  if (submittedError) return

  const submittedUserIds = new Set(
    (((submittedData as ParticipationUserRow[] | null) ?? [])
      .map((row) => row.user_id)
      .filter((id): id is string => typeof id === 'string' && id.length > 0))
  )

  if (submittedUserIds.size < eligibleUserIds.length) return

  await db
    .from('surveys')
    .update({
      status: 'closed',
      closes_at: new Date().toISOString(),
    })
    .eq('id', surveyId)
    .eq('status', 'open')
}

// ─── Draft Actions ────────────────────────────────────────────────────────────

export async function saveDraft(
  input: unknown
): Promise<{ success: true; data: ResponseDraft } | { success: false; error: string }> {
  const parsed = saveDraftSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const supabase = await createSupabaseServerClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) {
    return { success: false, error: 'Unauthorized' }
  }

  const { survey_id, answers, last_section_index } = parsed.data
  const nowIso = new Date().toISOString()
  const modernPayload = buildModernDraftPayload({
    survey_id,
    user_id: user.id,
    answers,
    last_section_index,
    nowIso,
  })

  // Upsert on (survey_id, user_id) — use supabaseAdmin to bypass RLS on write
  const modernAttempt = await db
    .from('response_drafts')
    .upsert(
      modernPayload,
      { onConflict: 'survey_id,user_id' }
    )
    .select()
    .single()

  if (!modernAttempt.error) {
    const normalized = normalizeDraftRow(modernAttempt.data as Record<string, unknown> | null)
    if (!normalized) return { success: false, error: 'Failed to load saved draft' }
    return { success: true, data: normalized }
  }

  if (!shouldRetryWithLegacyDraftColumns(modernAttempt.error)) {
    return { success: false, error: modernAttempt.error.message }
  }

  const legacyPayload = buildLegacyDraftPayload({
    survey_id,
    user_id: user.id,
    answers,
    last_section_index,
    nowIso,
  })

  const legacyAttempt = await db
    .from('response_drafts')
    .upsert(legacyPayload, { onConflict: 'survey_id,user_id' })
    .select()
    .single()

  if (legacyAttempt.error) return { success: false, error: legacyAttempt.error.message }

  const normalized = normalizeDraftRow(legacyAttempt.data as Record<string, unknown> | null)
  if (!normalized) return { success: false, error: 'Failed to load saved draft' }
  return { success: true, data: normalized }
}

export async function getMyDraft(
  surveyId: string
): Promise<{ success: true; data: ResponseDraft | null } | { success: false; error: string }> {
  const supabase = await createSupabaseServerClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) {
    return { success: false, error: 'Unauthorized' }
  }

  const { data, error } = await db
    .from('response_drafts')
    .select('*')
    .eq('survey_id', surveyId)
    .eq('user_id', user.id)
    .maybeSingle()

  if (error) return { success: false, error: error.message }
  return {
    success: true,
    data: normalizeDraftRow((data as Record<string, unknown> | null) ?? null),
  }
}

// ─── Submission Status ────────────────────────────────────────────────────────

export async function checkSubmissionStatus(
  surveyId: string
): Promise<{ success: true; data: SubmissionStatus } | { success: false; error: string }> {
  const supabase = await createSupabaseServerClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) {
    return { success: false, error: 'Unauthorized' }
  }

  // Check participation_tokens first (submitted)
  const { data: token, error: tokenError } = await db
    .from('participation_tokens')
    .select('id')
    .eq('survey_id', surveyId)
    .eq('user_id', user.id)
    .maybeSingle()

  if (tokenError) return { success: false, error: tokenError.message }
  if (token) return { success: true, data: 'submitted' as SubmissionStatus }

  // Check response_drafts (in progress)
  const { data: draft, error: draftError } = await db
    .from('response_drafts')
    .select('id')
    .eq('survey_id', surveyId)
    .eq('user_id', user.id)
    .maybeSingle()

  if (draftError) return { success: false, error: draftError.message }
  if (draft) return { success: true, data: 'in_progress' as SubmissionStatus }

  return { success: true, data: 'not_started' as SubmissionStatus }
}

// ─── Submit Response ──────────────────────────────────────────────────────────

export async function submitResponse(
  input: unknown
): Promise<{ success: true; data: SurveyResponse } | { success: false; error: string }> {
  const parsed = submitResponseSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const supabase = await createSupabaseServerClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) {
    return { success: false, error: 'Unauthorized' }
  }

  const { survey_id, answers } = parsed.data

  // (1) Check for duplicate submission via participation_tokens
  const { data: existingToken, error: tokenCheckError } = await db
    .from('participation_tokens')
    .select('id')
    .eq('survey_id', survey_id)
    .eq('user_id', user.id)
    .maybeSingle()

  if (tokenCheckError) return { success: false, error: tokenCheckError.message }
  if (existingToken) {
    return { success: false, error: 'You have already submitted a response to this survey.' }
  }

  // (2) Fetch survey to determine anonymity settings
  const modernSurveyFetch = await db
    .from('surveys')
    .select('is_anonymous')
    .eq('id', survey_id)
    .single()

  let surveyRow = modernSurveyFetch.data as Record<string, unknown> | null
  let surveyFetchError = modernSurveyFetch.error

  if (surveyFetchError && shouldRetryWithLegacySurveyColumns(surveyFetchError)) {
    const legacySurveyFetch = await db
      .from('surveys')
      .select('anonymous_mode')
      .eq('id', survey_id)
      .single()

    surveyRow = legacySurveyFetch.data as Record<string, unknown> | null
    surveyFetchError = legacySurveyFetch.error
  }

  const isAnonymous = getSurveyAnonymousFlag(surveyRow)
  if (surveyFetchError || isAnonymous === null) {
    return { success: false, error: 'Survey not found' }
  }

  // (3) Fetch profile snapshot metadata with modern+legacy compatibility
  const modernProfileFetch = await db
    .from('profiles')
    .select('department_id, role_id, tenure_band, work_type, departments(name), roles(name)')
    .eq('id', user.id)
    .maybeSingle()

  type ModernProfile = {
    department_id: string | null
    role_id: string | null
    tenure_band: string | null
    work_type: string | null
    departments: { name?: string } | Array<{ name?: string }> | null
    roles: { name?: string } | Array<{ name?: string }> | null
  }
  type LegacyProfile = {
    department: string | null
    role: string | null
    tenure_band: string | null
    work_type: string | null
  }

  let responseDepartment: string | null = null
  let responseRole: string | null = null
  let responseTenureBand: string | null = null
  let responseWorkType: string | null = null
  let tokenDepartmentId: string | null = null
  let tokenRoleId: string | null = null

  if (!modernProfileFetch.error) {
    const modern = modernProfileFetch.data as ModernProfile | null
    tokenDepartmentId = modern?.department_id ?? null
    tokenRoleId = modern?.role_id ?? null
    responseTenureBand = modern?.tenure_band ?? null
    responseWorkType = modern?.work_type ?? null
    responseDepartment = Array.isArray(modern?.departments)
      ? (modern?.departments[0]?.name ?? null)
      : (modern?.departments?.name ?? null)
    responseRole = Array.isArray(modern?.roles)
      ? (modern?.roles[0]?.name ?? null)
      : (modern?.roles?.name ?? null)
  } else if (getMissingColumnName(modernProfileFetch.error)) {
    const legacyProfileFetch = await db
      .from('profiles')
      .select('department, role, tenure_band, work_type')
      .eq('id', user.id)
      .maybeSingle()
    const legacy = legacyProfileFetch.data as LegacyProfile | null
    responseDepartment = legacy?.department ?? null
    responseRole = legacy?.role ?? null
    responseTenureBand = legacy?.tenure_band ?? null
    responseWorkType = legacy?.work_type ?? null
  }

  // (4) Try atomic submit RPC for faster writes and consistency
  const submitAt = new Date().toISOString()
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const rpcAttempt = await (db as any).rpc('submit_survey_response_atomic', {
    p_survey_id: survey_id,
    p_user_id: user.id,
    p_is_anonymous: isAnonymous,
    p_department: responseDepartment,
    p_role: responseRole,
    p_tenure_band: responseTenureBand,
    p_work_type: responseWorkType,
    p_answers: answers,
    p_token_department_id: tokenDepartmentId,
    p_token_role_id: tokenRoleId,
    p_submitted_at: submitAt,
  })

  if (!rpcAttempt.error) {
    const rpcResponseId = String(rpcAttempt.data ?? '')
    if (!rpcResponseId) {
      return { success: false, error: 'Failed to submit response' }
    }
    await autoCloseSurveyIfCompleted(survey_id)
    // Revalidate analytics pages so results update immediately after each submission
    revalidatePath('/leadership/dashboard')
    revalidatePath('/results')
    revalidatePath('/admin')
    return {
      success: true,
      data: {
        id: rpcResponseId,
        survey_id,
        user_id: isAnonymous ? null : user.id,
        is_anonymous: isAnonymous,
        submitted_at: submitAt as unknown as Date,
        department: responseDepartment,
        role: responseRole,
        tenure_band: responseTenureBand as SurveyResponse['tenure_band'],
        work_type: responseWorkType,
      },
    }
  }

  const rpcMissing = getMissingColumnName(rpcAttempt.error)
  if (!rpcMissing && !String(rpcAttempt.error.message ?? '').includes('submit_survey_response_atomic')) {
    return { success: false, error: rpcAttempt.error.message }
  }

  // (5) Legacy fallback path (existing behavior)
  // Insert response row first when RPC is unavailable.
  const { data: responseData, error: responseError } = await db
    .from('responses')
    .insert({
      survey_id,
      user_id: isAnonymous ? null : user.id,
      is_anonymous: isAnonymous,
      submitted_at: submitAt,
      department: responseDepartment,
      role: responseRole,
      tenure_band: responseTenureBand,
      work_type: responseWorkType,
    })
    .select()
    .single()

  if (responseError) return { success: false, error: responseError.message }

  const responseId = (responseData as { id: string }).id

  const answerRows = Object.entries(answers).map(([question_id, value]) => ({
    response_id: responseId,
    question_id,
    ...mapAnswerValueForStorage(value),
  }))

  const answerInsertPromise = answerRows.length > 0
    ? db.from('response_answers').insert(answerRows)
    : Promise.resolve({ error: null })

  const tokenInsertPromise = db
    .from('participation_tokens')
    .insert({
      survey_id,
      user_id: user.id,
      submitted_at: submitAt,
      department_id: tokenDepartmentId,
      role_id: tokenRoleId,
      tenure_band: responseTenureBand,
    })

  const [answersInsert, tokenInsert] = await Promise.all([answerInsertPromise, tokenInsertPromise])
  if (answersInsert.error) return { success: false, error: answersInsert.error.message }

  if (tokenInsert.error) {
    const missing = getMissingColumnName(tokenInsert.error)
    if (!missing) return { success: false, error: tokenInsert.error.message }

    const fallbackInsert = await db
      .from('participation_tokens')
      .insert({
        survey_id,
        user_id: user.id,
        submitted_at: submitAt,
      })
    if (fallbackInsert.error) return { success: false, error: fallbackInsert.error.message }
  }

  await db
    .from('response_drafts')
    .delete()
    .eq('survey_id', survey_id)
    .eq('user_id', user.id)

  await autoCloseSurveyIfCompleted(survey_id)
  revalidatePath('/leadership/dashboard')
  revalidatePath('/results')
  revalidatePath('/admin')

  return { success: true, data: responseData as SurveyResponse }
}
