'use server'
import { createSupabaseServerClient } from '@/lib/supabase/server'
import { supabaseAdmin } from '@/lib/supabase/admin'
import {
  saveDraftSchema,
  submitResponseSchema,
} from '@/lib/validations/survey'
import type {
  ResponseDraft,
  SurveyResponse,
  SubmissionStatus,
} from '@/lib/types/survey'

// Untyped admin client — Database schema is a stub; real types generated by Supabase CLI in Phase 3
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const db = supabaseAdmin as any

// ─── Draft Actions ────────────────────────────────────────────────────────────

export async function saveDraft(
  input: unknown
): Promise<{ success: true; data: ResponseDraft } | { success: false; error: string }> {
  const parsed = saveDraftSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const supabase = await createSupabaseServerClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) {
    return { success: false, error: 'Unauthorized' }
  }

  const { survey_id, answers, last_section_index } = parsed.data

  // Upsert on (survey_id, user_id) — use supabaseAdmin to bypass RLS on write
  const { data, error } = await db
    .from('response_drafts')
    .upsert(
      {
        survey_id,
        user_id: user.id,
        answers,
        last_section_index,
        updated_at: new Date().toISOString(),
      },
      { onConflict: 'survey_id,user_id' }
    )
    .select()
    .single()

  if (error) return { success: false, error: error.message }
  return { success: true, data: data as ResponseDraft }
}

export async function getMyDraft(
  surveyId: string
): Promise<{ success: true; data: ResponseDraft | null } | { success: false; error: string }> {
  const supabase = await createSupabaseServerClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) {
    return { success: false, error: 'Unauthorized' }
  }

  const { data, error } = await db
    .from('response_drafts')
    .select('*')
    .eq('survey_id', surveyId)
    .eq('user_id', user.id)
    .maybeSingle()

  if (error) return { success: false, error: error.message }
  return { success: true, data: data as ResponseDraft | null }
}

// ─── Submission Status ────────────────────────────────────────────────────────

export async function checkSubmissionStatus(
  surveyId: string
): Promise<{ success: true; data: SubmissionStatus } | { success: false; error: string }> {
  const supabase = await createSupabaseServerClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) {
    return { success: false, error: 'Unauthorized' }
  }

  // Check participation_tokens first (submitted)
  const { data: token, error: tokenError } = await db
    .from('participation_tokens')
    .select('id')
    .eq('survey_id', surveyId)
    .eq('user_id', user.id)
    .maybeSingle()

  if (tokenError) return { success: false, error: tokenError.message }
  if (token) return { success: true, data: 'submitted' as SubmissionStatus }

  // Check response_drafts (in progress)
  const { data: draft, error: draftError } = await db
    .from('response_drafts')
    .select('id')
    .eq('survey_id', surveyId)
    .eq('user_id', user.id)
    .maybeSingle()

  if (draftError) return { success: false, error: draftError.message }
  if (draft) return { success: true, data: 'in_progress' as SubmissionStatus }

  return { success: true, data: 'not_started' as SubmissionStatus }
}

// ─── Submit Response ──────────────────────────────────────────────────────────

export async function submitResponse(
  input: unknown
): Promise<{ success: true; data: SurveyResponse } | { success: false; error: string }> {
  const parsed = submitResponseSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const supabase = await createSupabaseServerClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) {
    return { success: false, error: 'Unauthorized' }
  }

  const { survey_id, answers } = parsed.data

  // (1) Check for duplicate submission via participation_tokens
  const { data: existingToken, error: tokenCheckError } = await db
    .from('participation_tokens')
    .select('id')
    .eq('survey_id', survey_id)
    .eq('user_id', user.id)
    .maybeSingle()

  if (tokenCheckError) return { success: false, error: tokenCheckError.message }
  if (existingToken) {
    return { success: false, error: 'You have already submitted a response to this survey.' }
  }

  // (2) Fetch survey to determine anonymity settings
  const { data: survey, error: surveyFetchError } = await db
    .from('surveys')
    .select('is_anonymous')
    .eq('id', survey_id)
    .single()

  if (surveyFetchError || !survey) {
    return { success: false, error: 'Survey not found' }
  }

  const isAnonymous = (survey as { is_anonymous: boolean }).is_anonymous

  // (3) Fetch profile snapshot metadata — stored as snapshot on responses, not as live FKs
  const { data: profile } = await db
    .from('profiles')
    .select('department, role, tenure_band, work_type')
    .eq('id', user.id)
    .maybeSingle()

  const profileSnapshot = profile as {
    department: string | null
    role: string | null
    tenure_band: string | null
    work_type: string | null
  } | null

  // (4) Insert response row
  // user_id is NULL for anonymous surveys — anonymity enforced at schema level
  const { data: responseData, error: responseError } = await db
    .from('responses')
    .insert({
      survey_id,
      user_id: isAnonymous ? null : user.id,
      is_anonymous: isAnonymous,
      submitted_at: new Date().toISOString(),
      department: profileSnapshot?.department ?? null,
      role: profileSnapshot?.role ?? null,
      tenure_band: profileSnapshot?.tenure_band ?? null,
      work_type: profileSnapshot?.work_type ?? null,
    })
    .select()
    .single()

  if (responseError) return { success: false, error: responseError.message }

  const responseId = (responseData as { id: string }).id

  // (5) Insert response_answers rows
  const answerRows = Object.entries(answers).map(([question_id, value]) => ({
    response_id: responseId,
    question_id,
    answer_text: typeof value === 'string' ? value : null,
    answer_numeric: typeof value === 'number' ? value : null,
    answer_options: Array.isArray(value) ? value : null,
  }))

  if (answerRows.length > 0) {
    const { error: answersError } = await db.from('response_answers').insert(answerRows)
    if (answersError) return { success: false, error: answersError.message }
  }

  // (6) Insert participation_tokens row
  // participation_tokens and responses share ONLY survey_id — structurally impossible to join them
  const { error: tokenInsertError } = await db
    .from('participation_tokens')
    .insert({
      survey_id,
      user_id: user.id,
      submitted_at: new Date().toISOString(),
    })

  if (tokenInsertError) return { success: false, error: tokenInsertError.message }

  // (7) Delete response_drafts row
  await db
    .from('response_drafts')
    .delete()
    .eq('survey_id', survey_id)
    .eq('user_id', user.id)

  return { success: true, data: responseData as SurveyResponse }
}
