'use server'
import { createSupabaseServerClient } from '@/lib/supabase/server'
import { supabaseAdmin } from '@/lib/supabase/admin'
import { normalizeRole } from '@/lib/constants/roles'
import {
  createSurveySchema,
  updateSurveySchema,
  createSectionSchema,
  updateSectionSchema,
  createQuestionSchema,
  updateQuestionSchema,
  reorderSectionsSchema,
  reorderQuestionsSchema,
  mapDimensionsSchema,
  transitionStatusSchema,
} from '@/lib/validations/survey'
import {
  buildLegacyQuestionPayload,
  buildLegacySurveyPayload,
  getMissingColumnName,
  normalizeQuestionRow,
  normalizeSurveyRow,
  shouldRetryWithLegacyQuestionWriteColumns,
  shouldRetryWithLegacySurveyWriteColumns,
} from './survey-compat'
import type {
  Survey,
  SurveySection,
  SurveyQuestion,
  SurveyStatus,
} from '@/lib/types/survey'

// Untyped admin client — Database schema is a stub; real types generated by Supabase CLI in Phase 3
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const db = supabaseAdmin as any

async function ensureDefaultSurveySection(surveyId: string): Promise<void> {
  const { count, error: countError } = await db
    .from('survey_sections')
    .select('*', { count: 'exact', head: true })
    .eq('survey_id', surveyId)

  if (countError || (count ?? 0) > 0) return

  await db
    .from('survey_sections')
    .insert({
      survey_id: surveyId,
      title: 'About You',
      description: 'Add respondent profile and context questions here.',
      target_roles: ['all'],
      display_order: 0,
    })
}

async function insertQuestionOptions(
  questionId: string,
  options: Array<{ text: string; display_order: number }>
): Promise<{ success: true } | { success: false; error: string }> {
  if (options.length === 0) return { success: true }

  const modernOptions = options.map((opt) => ({
    question_id: questionId,
    text: opt.text,
    value: opt.text,
    display_order: opt.display_order,
  }))

  const modernInsert = await db.from('question_options').insert(modernOptions)
  if (!modernInsert.error) return { success: true }

  const missingCol = getMissingColumnName(modernInsert.error)
  if (missingCol !== 'value') {
    return { success: false, error: modernInsert.error.message }
  }

  const legacyOptions = options.map((opt) => ({
    question_id: questionId,
    text: opt.text,
    display_order: opt.display_order,
  }))
  const legacyInsert = await db.from('question_options').insert(legacyOptions)
  if (legacyInsert.error) return { success: false, error: legacyInsert.error.message }
  return { success: true }
}

// ─── Transition Matrix ────────────────────────────────────────────────────────

const ALLOWED_TRANSITIONS: Record<SurveyStatus, SurveyStatus[]> = {
  draft: ['scheduled', 'open'],
  scheduled: ['open', 'draft'],
  open: ['closed'],
  closed: [],
}

// ─── Survey CRUD ──────────────────────────────────────────────────────────────

export async function createSurvey(
  input: unknown
): Promise<{ success: true; data: Survey } | { success: false; error: string }> {
  const parsed = createSurveySchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const supabase = await createSupabaseServerClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) {
    return { success: false, error: 'Unauthorized' }
  }

  const originalPayload: Record<string, unknown> = { ...parsed.data, created_by: user.id }
  let payload: Record<string, unknown> = { ...originalPayload }
  let lastError: { message?: string; code?: string } | null = null

  for (let attempt = 0; attempt < 6; attempt++) {
    const insertResult = await db
      .from('surveys')
      .insert(payload)
      .select()
      .single()

    if (!insertResult.error) {
      const survey = normalizeSurveyRow(insertResult.data as Record<string, unknown>)
      await ensureDefaultSurveySection(survey.id)
      return { success: true, data: survey }
    }

    lastError = insertResult.error as { message?: string; code?: string }
    if (!shouldRetryWithLegacySurveyWriteColumns(lastError)) {
      return { success: false, error: insertResult.error.message }
    }

    const missingColumn = getMissingColumnName(lastError)
    if (missingColumn === 'is_anonymous') {
      delete payload.is_anonymous
      payload.anonymous_mode = Boolean(parsed.data.is_anonymous)
      continue
    }
    if (missingColumn === 'anonymous_mode') {
      delete payload.anonymous_mode
      payload.is_anonymous = Boolean(parsed.data.is_anonymous)
      continue
    }
    if (missingColumn) {
      delete payload[missingColumn]
      continue
    }

    if ('public_link_enabled' in payload) {
      delete payload.public_link_enabled
      continue
    }

    payload = buildLegacySurveyPayload({ ...originalPayload })
  }

  if (!lastError) return { success: false, error: 'Failed to create survey' }
  return { success: false, error: lastError.message ?? 'Failed to create survey' }
}

export async function updateSurvey(
  input: unknown
): Promise<{ success: true; data: Survey } | { success: false; error: string }> {
  const parsed = updateSurveySchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const { id, ...fields } = parsed.data
  const modernUpdate = await db
    .from('surveys')
    .update(fields)
    .eq('id', id)
    .select()
    .single()

  if (!modernUpdate.error) {
    return { success: true, data: normalizeSurveyRow(modernUpdate.data as Record<string, unknown>) }
  }

  if (!shouldRetryWithLegacySurveyWriteColumns(modernUpdate.error)) {
    return { success: false, error: modernUpdate.error.message }
  }

  const legacyFields = buildLegacySurveyPayload(fields)
  const legacyUpdate = await db
    .from('surveys')
    .update(legacyFields)
    .eq('id', id)
    .select()
    .single()

  if (legacyUpdate.error) return { success: false, error: legacyUpdate.error.message }
  const survey = normalizeSurveyRow(legacyUpdate.data as Record<string, unknown>)
  await ensureDefaultSurveySection(survey.id)
  return { success: true, data: survey }
}

// ─── Section Actions ──────────────────────────────────────────────────────────

export async function createSection(
  input: unknown
): Promise<{ success: true; data: SurveySection } | { success: false; error: string }> {
  const parsed = createSectionSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const { count } = await db
    .from('survey_sections')
    .select('*', { count: 'exact', head: true })
    .eq('survey_id', parsed.data.survey_id)

  const { data, error } = await db
    .from('survey_sections')
    .insert({ ...parsed.data, display_order: (count ?? 0) })
    .select()
    .single()

  if (error) return { success: false, error: error.message }
  return { success: true, data: data as SurveySection }
}

export async function updateSection(
  input: unknown
): Promise<{ success: true; data: SurveySection } | { success: false; error: string }> {
  const parsed = updateSectionSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const { id, ...fields } = parsed.data
  const { data, error } = await db
    .from('survey_sections')
    .update(fields)
    .eq('id', id)
    .select()
    .single()

  if (error) return { success: false, error: error.message }
  return { success: true, data: data as SurveySection }
}

export async function reorderSections(
  input: unknown
): Promise<{ success: true } | { success: false; error: string }> {
  const parsed = reorderSectionsSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  for (const item of parsed.data.items) {
    const { error } = await db
      .from('survey_sections')
      .update({ display_order: item.display_order })
      .eq('id', item.id)
    if (error) return { success: false, error: error.message }
  }

  return { success: true }
}

// ─── Question Actions ─────────────────────────────────────────────────────────

export async function createQuestion(
  input: unknown
): Promise<{ success: true; data: SurveyQuestion } | { success: false; error: string }> {
  const parsed = createQuestionSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const { options, ...questionFields } = parsed.data

  const { count } = await db
    .from('questions')
    .select('*', { count: 'exact', head: true })
    .eq('survey_section_id', questionFields.survey_section_id)

  const stableQuestionId = crypto.randomUUID()
  const originalPayload: Record<string, unknown> = {
    ...questionFields,
    display_order: (count ?? 0),
    stable_question_id: stableQuestionId,
  }
  let payload: Record<string, unknown> = { ...originalPayload }
  let questionData: unknown = null
  let lastError: { message?: string } | null = null

  for (let attempt = 0; attempt < 6; attempt++) {
    const insertResult = await db
      .from('questions')
      .insert(payload)
      .select()
      .single()

    if (!insertResult.error) {
      questionData = insertResult.data
      break
    }

    lastError = insertResult.error as { message?: string }
    if (!shouldRetryWithLegacyQuestionWriteColumns(insertResult.error)) {
      return { success: false, error: insertResult.error.message }
    }

    const missingCol = getMissingColumnName(insertResult.error)
    if (missingCol === 'question_type') {
      delete payload.question_type
      payload.type = parsed.data.question_type
      continue
    }
    if (missingCol === 'is_required') {
      delete payload.is_required
      payload.required = parsed.data.is_required
      continue
    }
    if (missingCol === 'conditional_rule') {
      delete payload.conditional_rule
      payload.conditional_config =
        parsed.data.conditional_rule && typeof parsed.data.conditional_rule === 'object'
          ? parsed.data.conditional_rule
          : {}
      continue
    }
    if (missingCol === 'stable_question_id') {
      delete payload.stable_question_id
      continue
    }
    if (missingCol) {
      delete payload[missingCol]
      continue
    }

    payload = buildLegacyQuestionPayload(payload)
  }

  if (!questionData) {
    return { success: false, error: lastError?.message ?? 'Failed to create question' }
  }

  if (options && options.length > 0) {
    const optionResult = await insertQuestionOptions((questionData as { id: string }).id, options)
    if (!optionResult.success) return optionResult
  }

  return { success: true, data: normalizeQuestionRow(questionData as Record<string, unknown>) }
}

export async function updateQuestion(
  input: unknown
): Promise<{ success: true; data: SurveyQuestion } | { success: false; error: string }> {
  const parsed = updateQuestionSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const { id, options, ...fields } = parsed.data
  const modernUpdate = await db
    .from('questions')
    .update(fields)
    .eq('id', id)
    .select()
    .single()

  let data: unknown = modernUpdate.data
  if (modernUpdate.error) {
    if (!shouldRetryWithLegacyQuestionWriteColumns(modernUpdate.error)) {
      return { success: false, error: modernUpdate.error.message }
    }

    const legacyFields = buildLegacyQuestionPayload(fields as Record<string, unknown>)
    const legacyUpdate = await db
      .from('questions')
      .update(legacyFields)
      .eq('id', id)
      .select()
      .single()

    if (legacyUpdate.error) return { success: false, error: legacyUpdate.error.message }
    data = legacyUpdate.data
  }

  if (options !== undefined && id) {
    await db.from('question_options').delete().eq('question_id', id)
    if (options.length > 0) {
      const optionResult = await insertQuestionOptions(id, options)
      if (!optionResult.success) return optionResult
    }
  }

  return { success: true, data: normalizeQuestionRow(data as Record<string, unknown>) }
}

export async function reorderQuestions(
  input: unknown
): Promise<{ success: true } | { success: false; error: string }> {
  const parsed = reorderQuestionsSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  for (const item of parsed.data.items) {
    const { error } = await db
      .from('questions')
      .update({ display_order: item.display_order })
      .eq('id', item.id)
    if (error) return { success: false, error: error.message }
  }

  return { success: true }
}

export async function deleteQuestion(
  questionId: string
): Promise<{ success: true } | { success: false; error: string }> {
  const { error } = await db.from('questions').delete().eq('id', questionId)
  if (error) return { success: false, error: error.message }
  return { success: true }
}

// ─── Dimension Mapping ────────────────────────────────────────────────────────

export async function mapQuestionDimensions(
  input: unknown
): Promise<{ success: true } | { success: false; error: string }> {
  const parsed = mapDimensionsSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const { question_id, dimension_ids } = parsed.data

  const { error: deleteError } = await db
    .from('question_dimension_map')
    .delete()
    .eq('question_id', question_id)

  if (deleteError) return { success: false, error: deleteError.message }

  if (dimension_ids.length > 0) {
    const { error: insertError } = await db
      .from('question_dimension_map')
      .insert(dimension_ids.map((dimension_id: string) => ({ question_id, dimension_id })))
    if (insertError) return { success: false, error: insertError.message }
  }

  return { success: true }
}

// ─── Lifecycle Transition ─────────────────────────────────────────────────────

export async function transitionSurveyStatus(
  input: unknown
): Promise<{ success: true; data: Survey } | { success: false; error: string }> {
  const parsed = transitionStatusSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const { survey_id, to_status, opens_at } = parsed.data

  const { data: current, error: fetchError } = await db
    .from('surveys')
    .select('status')
    .eq('id', survey_id)
    .single()

  if (fetchError || !current) {
    return { success: false, error: 'Survey not found' }
  }

  const currentStatus = (current as { status: SurveyStatus }).status
  const allowed = ALLOWED_TRANSITIONS[currentStatus]

  if (!allowed.includes(to_status)) {
    return { success: false, error: 'Invalid status transition' }
  }

  const updateFields: Record<string, unknown> = { status: to_status }
  if (opens_at) updateFields.opens_at = opens_at

  const { data, error } = await db
    .from('surveys')
    .update(updateFields)
    .eq('id', survey_id)
    .select()
    .single()

  if (error) return { success: false, error: error.message }
  return { success: true, data: data as Survey }
}

// ─── Duplicate Survey ─────────────────────────────────────────────────────────

export async function duplicateSurvey(
  surveyId: string
): Promise<{ success: true; data: Survey } | { success: false; error: string }> {
  // Fetch source survey
  const { data: sourceSurvey, error: surveyFetchError } = await db
    .from('surveys')
    .select('*')
    .eq('id', surveyId)
    .single()

  if (surveyFetchError || !sourceSurvey) {
    return { success: false, error: 'Survey not found' }
  }

  // Fetch all sections
  const { data: sections, error: sectionsFetchError } = await db
    .from('survey_sections')
    .select('*')
    .eq('survey_id', surveyId)
    .order('display_order')

  if (sectionsFetchError) {
    return { success: false, error: sectionsFetchError.message }
  }

  const sectionList = (sections ?? []) as Array<SurveySection & { created_at?: string }>
  const sectionIds = sectionList.map((s) => s.id)

  let questions: Array<SurveyQuestion & { created_at?: string }> = []
  let questionIds: string[] = []

  if (sectionIds.length > 0) {
    const { data: qs, error: questionsFetchError } = await db
      .from('questions')
      .select('*')
      .in('survey_section_id', sectionIds)
      .order('display_order')

    if (questionsFetchError) {
      return { success: false, error: questionsFetchError.message }
    }

    questions = (qs ?? []) as Array<SurveyQuestion & { created_at?: string }>
    questionIds = questions.map((q) => q.id)
  }

  let allOptions: Array<{ id: string; question_id: string; text: string; display_order: number }> = []
  if (questionIds.length > 0) {
    const { data: opts, error: optsFetchError } = await db
      .from('question_options')
      .select('*')
      .in('question_id', questionIds)
      .order('display_order')

    if (optsFetchError) {
      return { success: false, error: optsFetchError.message }
    }
    allOptions = (opts ?? []) as typeof allOptions
  }

  let allDimensionMaps: Array<{ question_id: string; dimension_id: string }> = []
  if (questionIds.length > 0) {
    const { data: dimMaps, error: dimMapsFetchError } = await db
      .from('question_dimension_map')
      .select('*')
      .in('question_id', questionIds)

    if (dimMapsFetchError) {
      return { success: false, error: dimMapsFetchError.message }
    }
    allDimensionMaps = (dimMaps ?? []) as typeof allDimensionMaps
  }

  // Create new survey (status='draft', new id)
  const { id: _id, created_at: _ca, status: _st, ...surveyFields } = sourceSurvey as Survey & { created_at: string }

  const { data: newSurvey, error: newSurveyError } = await db
    .from('surveys')
    .insert({
      ...surveyFields,
      status: 'draft',
      title: `Copy of ${(sourceSurvey as Survey).title}`,
    })
    .select()
    .single()

  if (newSurveyError || !newSurvey) {
    return { success: false, error: newSurveyError?.message ?? 'Failed to create survey copy' }
  }

  const newSurveyId = (newSurvey as { id: string }).id

  // Duplicate sections — build old→new id map
  const sectionIdMap: Record<string, string> = {}
  for (const section of sectionList) {
    const { id: sectionId, survey_id: _sv, created_at: _sca, ...sectionFields } = section
    const { data: newSection, error: newSectionError } = await db
      .from('survey_sections')
      .insert({ ...sectionFields, survey_id: newSurveyId })
      .select()
      .single()

    if (newSectionError || !newSection) {
      return { success: false, error: newSectionError?.message ?? 'Failed to copy section' }
    }
    sectionIdMap[sectionId] = (newSection as { id: string }).id
  }

  // Duplicate questions — preserve stable_question_id
  const questionIdMap: Record<string, string> = {}
  for (const question of questions) {
    const { id: questionId, survey_section_id, created_at: _qca, ...questionFields } = question
    const newSectionId = sectionIdMap[survey_section_id]
    if (!newSectionId) continue

    const { data: newQuestion, error: newQuestionError } = await db
      .from('questions')
      .insert({ ...questionFields, survey_section_id: newSectionId })
      .select()
      .single()

    if (newQuestionError || !newQuestion) {
      return { success: false, error: newQuestionError?.message ?? 'Failed to copy question' }
    }
    questionIdMap[questionId] = (newQuestion as { id: string }).id
  }

  // Duplicate question_options
  for (const option of allOptions) {
    const { id: _optId, question_id, ...optFields } = option
    const newQuestionId = questionIdMap[question_id]
    if (!newQuestionId) continue

    const { error: optError } = await db
      .from('question_options')
      .insert({ ...optFields, question_id: newQuestionId })

    if (optError) return { success: false, error: optError.message }
  }

  // Duplicate question_dimension_map
  for (const dimMap of allDimensionMaps) {
    const { question_id, dimension_id } = dimMap
    const newQuestionId = questionIdMap[question_id]
    if (!newQuestionId) continue

    const { error: dimError } = await db
      .from('question_dimension_map')
      .insert({ question_id: newQuestionId, dimension_id })

    if (dimError) return { success: false, error: dimError.message }
  }

  return { success: true, data: newSurvey as Survey }
}

// ─── Delete Survey ────────────────────────────────────────────────────────────

export async function deleteSurvey(
  surveyId: string
): Promise<{ success: true } | { success: false; error: string }> {
  const supabase = await createSupabaseServerClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) return { success: false, error: 'Unauthorized' }

  const role = normalizeRole(user.app_metadata?.role as string | undefined)
  if (role !== 'admin') return { success: false, error: 'Forbidden' }

  const { data: surveyData, error: surveyError } = await db
    .from('surveys')
    .select('id')
    .eq('id', surveyId)
    .single()

  if (surveyError || !surveyData) return { success: false, error: 'Survey not found' }

  const { count: snapshotCount, error: snapshotError } = await db
    .from('publication_snapshots')
    .select('*', { count: 'exact', head: true })
    .eq('survey_id', surveyId)

  if (snapshotError) return { success: false, error: snapshotError.message }
  if ((snapshotCount ?? 0) > 0) {
    return { success: false, error: 'Cannot delete a survey with published results.' }
  }

  const { error: actionItemsError } = await db
    .from('action_items')
    .update({ survey_id: null })
    .eq('survey_id', surveyId)
  if (actionItemsError) return { success: false, error: actionItemsError.message }

  const { error: draftsError } = await db
    .from('response_drafts')
    .delete()
    .eq('survey_id', surveyId)
  if (draftsError) return { success: false, error: draftsError.message }

  const { error: tokensError } = await db
    .from('participation_tokens')
    .delete()
    .eq('survey_id', surveyId)
  if (tokensError) return { success: false, error: tokensError.message }

  const { error: responsesError } = await db
    .from('responses')
    .delete()
    .eq('survey_id', surveyId)
  if (responsesError) return { success: false, error: responsesError.message }

  const { error: metricsError } = await db
    .from('derived_metrics')
    .delete()
    .eq('survey_id', surveyId)
  if (metricsError) return { success: false, error: metricsError.message }

  const { error: themesError } = await db
    .from('qualitative_themes')
    .delete()
    .eq('survey_id', surveyId)
  if (themesError) return { success: false, error: themesError.message }

  const { error: deleteError } = await db
    .from('surveys')
    .delete()
    .eq('id', surveyId)

  if (deleteError) return { success: false, error: deleteError.message }
  return { success: true }
}
