'use server'
import { createSupabaseServerClient } from '@/lib/supabase/server'
import { supabaseAdmin } from '@/lib/supabase/admin'
import {
  createSurveySchema,
  updateSurveySchema,
  createSectionSchema,
  updateSectionSchema,
  createQuestionSchema,
  updateQuestionSchema,
  reorderSectionsSchema,
  reorderQuestionsSchema,
  mapDimensionsSchema,
  transitionStatusSchema,
} from '@/lib/validations/survey'
import type {
  Survey,
  SurveySection,
  SurveyQuestion,
  SurveyStatus,
} from '@/lib/types/survey'

// Untyped admin client — Database schema is a stub; real types generated by Supabase CLI in Phase 3
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const db = supabaseAdmin as any

// ─── Transition Matrix ────────────────────────────────────────────────────────

const ALLOWED_TRANSITIONS: Record<SurveyStatus, SurveyStatus[]> = {
  draft: ['scheduled', 'open'],
  scheduled: ['open', 'draft'],
  open: ['closed'],
  closed: [],
}

// ─── Survey CRUD ──────────────────────────────────────────────────────────────

export async function createSurvey(
  input: unknown
): Promise<{ success: true; data: Survey } | { success: false; error: string }> {
  const parsed = createSurveySchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const supabase = await createSupabaseServerClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) {
    return { success: false, error: 'Unauthorized' }
  }

  const { data, error } = await db
    .from('surveys')
    .insert({ ...parsed.data, created_by: user.id })
    .select()
    .single()

  if (error) return { success: false, error: error.message }
  return { success: true, data: data as Survey }
}

export async function updateSurvey(
  input: unknown
): Promise<{ success: true; data: Survey } | { success: false; error: string }> {
  const parsed = updateSurveySchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const { id, ...fields } = parsed.data
  const { data, error } = await db
    .from('surveys')
    .update(fields)
    .eq('id', id)
    .select()
    .single()

  if (error) return { success: false, error: error.message }
  return { success: true, data: data as Survey }
}

// ─── Section Actions ──────────────────────────────────────────────────────────

export async function createSection(
  input: unknown
): Promise<{ success: true; data: SurveySection } | { success: false; error: string }> {
  const parsed = createSectionSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const { count } = await db
    .from('survey_sections')
    .select('*', { count: 'exact', head: true })
    .eq('survey_id', parsed.data.survey_id)

  const { data, error } = await db
    .from('survey_sections')
    .insert({ ...parsed.data, display_order: (count ?? 0) })
    .select()
    .single()

  if (error) return { success: false, error: error.message }
  return { success: true, data: data as SurveySection }
}

export async function updateSection(
  input: unknown
): Promise<{ success: true; data: SurveySection } | { success: false; error: string }> {
  const parsed = updateSectionSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const { id, ...fields } = parsed.data
  const { data, error } = await db
    .from('survey_sections')
    .update(fields)
    .eq('id', id)
    .select()
    .single()

  if (error) return { success: false, error: error.message }
  return { success: true, data: data as SurveySection }
}

export async function reorderSections(
  input: unknown
): Promise<{ success: true } | { success: false; error: string }> {
  const parsed = reorderSectionsSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  for (const item of parsed.data.items) {
    const { error } = await db
      .from('survey_sections')
      .update({ display_order: item.display_order })
      .eq('id', item.id)
    if (error) return { success: false, error: error.message }
  }

  return { success: true }
}

// ─── Question Actions ─────────────────────────────────────────────────────────

export async function createQuestion(
  input: unknown
): Promise<{ success: true; data: SurveyQuestion } | { success: false; error: string }> {
  const parsed = createQuestionSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const { options, ...questionFields } = parsed.data

  const { count } = await db
    .from('questions')
    .select('*', { count: 'exact', head: true })
    .eq('survey_section_id', questionFields.survey_section_id)

  const stableQuestionId = crypto.randomUUID()

  const { data: questionData, error: questionError } = await db
    .from('questions')
    .insert({
      ...questionFields,
      display_order: (count ?? 0),
      stable_question_id: stableQuestionId,
    })
    .select()
    .single()

  if (questionError) return { success: false, error: questionError.message }

  if (options && options.length > 0) {
    const { error: optionsError } = await db
      .from('question_options')
      .insert(
        options.map((opt: { text: string; display_order: number }) => ({
          question_id: (questionData as { id: string }).id,
          text: opt.text,
          display_order: opt.display_order,
        }))
      )
    if (optionsError) return { success: false, error: optionsError.message }
  }

  return { success: true, data: questionData as SurveyQuestion }
}

export async function updateQuestion(
  input: unknown
): Promise<{ success: true; data: SurveyQuestion } | { success: false; error: string }> {
  const parsed = updateQuestionSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const { id, options, ...fields } = parsed.data
  const { data, error } = await db
    .from('questions')
    .update(fields)
    .eq('id', id)
    .select()
    .single()

  if (error) return { success: false, error: error.message }

  if (options !== undefined && id) {
    await db.from('question_options').delete().eq('question_id', id)
    if (options.length > 0) {
      await db.from('question_options').insert(
        options.map((opt: { text: string; display_order: number }) => ({
          question_id: id,
          text: opt.text,
          display_order: opt.display_order,
        }))
      )
    }
  }

  return { success: true, data: data as SurveyQuestion }
}

export async function reorderQuestions(
  input: unknown
): Promise<{ success: true } | { success: false; error: string }> {
  const parsed = reorderQuestionsSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  for (const item of parsed.data.items) {
    const { error } = await db
      .from('questions')
      .update({ display_order: item.display_order })
      .eq('id', item.id)
    if (error) return { success: false, error: error.message }
  }

  return { success: true }
}

export async function deleteQuestion(
  questionId: string
): Promise<{ success: true } | { success: false; error: string }> {
  const { error } = await db.from('questions').delete().eq('id', questionId)
  if (error) return { success: false, error: error.message }
  return { success: true }
}

// ─── Dimension Mapping ────────────────────────────────────────────────────────

export async function mapQuestionDimensions(
  input: unknown
): Promise<{ success: true } | { success: false; error: string }> {
  const parsed = mapDimensionsSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const { question_id, dimension_ids } = parsed.data

  const { error: deleteError } = await db
    .from('question_dimension_map')
    .delete()
    .eq('question_id', question_id)

  if (deleteError) return { success: false, error: deleteError.message }

  if (dimension_ids.length > 0) {
    const { error: insertError } = await db
      .from('question_dimension_map')
      .insert(dimension_ids.map((dimension_id: string) => ({ question_id, dimension_id })))
    if (insertError) return { success: false, error: insertError.message }
  }

  return { success: true }
}

// ─── Lifecycle Transition ─────────────────────────────────────────────────────

export async function transitionSurveyStatus(
  input: unknown
): Promise<{ success: true; data: Survey } | { success: false; error: string }> {
  const parsed = transitionStatusSchema.safeParse(input)
  if (!parsed.success) {
    return { success: false, error: parsed.error.errors[0].message }
  }

  const { survey_id, to_status, opens_at } = parsed.data

  const { data: current, error: fetchError } = await db
    .from('surveys')
    .select('status')
    .eq('id', survey_id)
    .single()

  if (fetchError || !current) {
    return { success: false, error: 'Survey not found' }
  }

  const currentStatus = (current as { status: SurveyStatus }).status
  const allowed = ALLOWED_TRANSITIONS[currentStatus]

  if (!allowed.includes(to_status)) {
    return { success: false, error: 'Invalid status transition' }
  }

  const updateFields: Record<string, unknown> = { status: to_status }
  if (opens_at) updateFields.opens_at = opens_at

  const { data, error } = await db
    .from('surveys')
    .update(updateFields)
    .eq('id', survey_id)
    .select()
    .single()

  if (error) return { success: false, error: error.message }
  return { success: true, data: data as Survey }
}

// ─── Duplicate Survey ─────────────────────────────────────────────────────────

export async function duplicateSurvey(
  surveyId: string
): Promise<{ success: true; data: Survey } | { success: false; error: string }> {
  // Fetch source survey
  const { data: sourceSurvey, error: surveyFetchError } = await db
    .from('surveys')
    .select('*')
    .eq('id', surveyId)
    .single()

  if (surveyFetchError || !sourceSurvey) {
    return { success: false, error: 'Survey not found' }
  }

  // Fetch all sections
  const { data: sections, error: sectionsFetchError } = await db
    .from('survey_sections')
    .select('*')
    .eq('survey_id', surveyId)
    .order('display_order')

  if (sectionsFetchError) {
    return { success: false, error: sectionsFetchError.message }
  }

  const sectionList = (sections ?? []) as Array<SurveySection & { created_at?: string }>
  const sectionIds = sectionList.map((s) => s.id)

  let questions: Array<SurveyQuestion & { created_at?: string }> = []
  let questionIds: string[] = []

  if (sectionIds.length > 0) {
    const { data: qs, error: questionsFetchError } = await db
      .from('questions')
      .select('*')
      .in('survey_section_id', sectionIds)
      .order('display_order')

    if (questionsFetchError) {
      return { success: false, error: questionsFetchError.message }
    }

    questions = (qs ?? []) as Array<SurveyQuestion & { created_at?: string }>
    questionIds = questions.map((q) => q.id)
  }

  let allOptions: Array<{ id: string; question_id: string; text: string; display_order: number }> = []
  if (questionIds.length > 0) {
    const { data: opts, error: optsFetchError } = await db
      .from('question_options')
      .select('*')
      .in('question_id', questionIds)
      .order('display_order')

    if (optsFetchError) {
      return { success: false, error: optsFetchError.message }
    }
    allOptions = (opts ?? []) as typeof allOptions
  }

  let allDimensionMaps: Array<{ question_id: string; dimension_id: string }> = []
  if (questionIds.length > 0) {
    const { data: dimMaps, error: dimMapsFetchError } = await db
      .from('question_dimension_map')
      .select('*')
      .in('question_id', questionIds)

    if (dimMapsFetchError) {
      return { success: false, error: dimMapsFetchError.message }
    }
    allDimensionMaps = (dimMaps ?? []) as typeof allDimensionMaps
  }

  // Create new survey (status='draft', new id)
  const { id: _id, created_at: _ca, status: _st, ...surveyFields } = sourceSurvey as Survey & { created_at: string }

  const { data: newSurvey, error: newSurveyError } = await db
    .from('surveys')
    .insert({
      ...surveyFields,
      status: 'draft',
      title: `Copy of ${(sourceSurvey as Survey).title}`,
    })
    .select()
    .single()

  if (newSurveyError || !newSurvey) {
    return { success: false, error: newSurveyError?.message ?? 'Failed to create survey copy' }
  }

  const newSurveyId = (newSurvey as { id: string }).id

  // Duplicate sections — build old→new id map
  const sectionIdMap: Record<string, string> = {}
  for (const section of sectionList) {
    const { id: sectionId, survey_id: _sv, created_at: _sca, ...sectionFields } = section
    const { data: newSection, error: newSectionError } = await db
      .from('survey_sections')
      .insert({ ...sectionFields, survey_id: newSurveyId })
      .select()
      .single()

    if (newSectionError || !newSection) {
      return { success: false, error: newSectionError?.message ?? 'Failed to copy section' }
    }
    sectionIdMap[sectionId] = (newSection as { id: string }).id
  }

  // Duplicate questions — preserve stable_question_id
  const questionIdMap: Record<string, string> = {}
  for (const question of questions) {
    const { id: questionId, survey_section_id, created_at: _qca, ...questionFields } = question
    const newSectionId = sectionIdMap[survey_section_id]
    if (!newSectionId) continue

    const { data: newQuestion, error: newQuestionError } = await db
      .from('questions')
      .insert({ ...questionFields, survey_section_id: newSectionId })
      .select()
      .single()

    if (newQuestionError || !newQuestion) {
      return { success: false, error: newQuestionError?.message ?? 'Failed to copy question' }
    }
    questionIdMap[questionId] = (newQuestion as { id: string }).id
  }

  // Duplicate question_options
  for (const option of allOptions) {
    const { id: _optId, question_id, ...optFields } = option
    const newQuestionId = questionIdMap[question_id]
    if (!newQuestionId) continue

    const { error: optError } = await db
      .from('question_options')
      .insert({ ...optFields, question_id: newQuestionId })

    if (optError) return { success: false, error: optError.message }
  }

  // Duplicate question_dimension_map
  for (const dimMap of allDimensionMaps) {
    const { question_id, dimension_id } = dimMap
    const newQuestionId = questionIdMap[question_id]
    if (!newQuestionId) continue

    const { error: dimError } = await db
      .from('question_dimension_map')
      .insert({ question_id: newQuestionId, dimension_id })

    if (dimError) return { success: false, error: dimError.message }
  }

  return { success: true, data: newSurvey as Survey }
}
