import { cookies } from 'next/headers'
import { supabaseAdmin } from '@/lib/supabase/admin'
import PublicSurveyClient from './PublicSurveyClient'
import { normalizeQuestionRow } from '@/lib/actions/survey-compat'
import type {
  Survey,
  SurveySection,
  SurveyQuestion,
  QuestionOption,
} from '@/lib/types/survey'

// Untyped admin client — Database schema is a stub; real types generated by Supabase CLI in Phase 3
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const db = supabaseAdmin as any

interface PageProps {
  params: Promise<{ id: string }>
}

export default async function PublicSurveyPage({ params }: PageProps) {
  const { id: surveyId } = await params

  // Use supabaseAdmin — no auth user context available on public route
  const { data: surveyData, error: surveyError } = await db
    .from('surveys')
    .select('*')
    .eq('id', surveyId)
    .single()

  // Survey not found or unavailable
  if (surveyError || !surveyData) {
    return <SurveyUnavailable reason="not_found" />
  }

  const survey = surveyData as Survey

  // Check public_link_enabled and status
  if (!survey.public_link_enabled || survey.status !== 'open') {
    return <SurveyUnavailable reason="not_available" surveyTitle={survey.title} />
  }

  // Cookie-based deduplication check (server-side read)
  const cookieStore = await cookies()
  const cookieName = `survey_submitted_${surveyId}`
  const alreadySubmitted = cookieStore.get(cookieName)

  if (alreadySubmitted) {
    return <PublicAlreadySubmitted surveyTitle={survey.title} />
  }

  // Fetch all sections (no role filtering for public respondents — all sections shown)
  const { data: sectionsData } = await db
    .from('survey_sections')
    .select('*')
    .eq('survey_id', surveyId)
    .order('display_order', { ascending: true })

  const sections: SurveySection[] = (sectionsData ?? []) as SurveySection[]

  if (sections.length === 0) {
    return <SurveyUnavailable reason="no_sections" surveyTitle={survey.title} />
  }

  // Fetch questions for all sections
  const sectionIds = sections.map((s) => s.id)
  const { data: questionsData } = await db
    .from('questions')
    .select('*')
    .in('survey_section_id', sectionIds)
    .order('display_order', { ascending: true })

  const allQuestions: SurveyQuestion[] = ((questionsData ?? []) as Record<string, unknown>[]).map(normalizeQuestionRow)

  const questionsMap: Record<string, SurveyQuestion[]> = {}
  for (const section of sections) {
    questionsMap[section.id] = allQuestions.filter((q) => q.survey_section_id === section.id)
  }

  // Fetch options for all questions
  const questionIds = allQuestions.map((q) => q.id)
  const optionsMap: Record<string, QuestionOption[]> = {}

  if (questionIds.length > 0) {
    const { data: optionsData } = await db
      .from('question_options')
      .select('*')
      .in('question_id', questionIds)
      .order('display_order', { ascending: true })

    const allOptions: QuestionOption[] = (optionsData ?? []) as QuestionOption[]
    for (const option of allOptions) {
      if (!optionsMap[option.question_id]) {
        optionsMap[option.question_id] = []
      }
      optionsMap[option.question_id].push(option)
    }
  }

  const confirmationPath = `/survey/public/${surveyId}/confirmation`

  return (
    <div className="min-h-screen bg-bg">
      <div className="max-w-3xl mx-auto p-8">
        <div className="mb-6">
          <h1 className="text-2xl font-extrabold tracking-snug text-fg">{survey.title}</h1>
          {survey.description && (
            <p className="text-fg-muted mt-1">{survey.description}</p>
          )}
          <p className="text-xs text-fg-subtle mt-2">
            Your response is anonymous and collected without a login.
          </p>
        </div>
        <PublicSurveyClient
          survey={survey}
          sections={sections}
          questionsMap={questionsMap}
          optionsMap={optionsMap}
          confirmationPath={confirmationPath}
        />
      </div>
    </div>
  )
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function SurveyUnavailable({
  reason,
  surveyTitle,
}: {
  reason: 'not_found' | 'not_available' | 'no_sections'
  surveyTitle?: string
}) {
  const message =
    reason === 'not_found'
      ? 'This survey link is invalid or the survey no longer exists.'
      : reason === 'no_sections'
        ? 'This survey has no questions to display.'
        : 'This survey is not currently available for public responses.'

  return (
    <div className="min-h-screen bg-bg flex items-center justify-center p-8">
      <div className="bg-surface border border-border rounded-lg shadow-sm p-8 max-w-md w-full text-center">
        {surveyTitle && (
          <h1 className="text-xl font-bold tracking-snug text-fg mb-2">{surveyTitle}</h1>
        )}
        <p className="text-fg-muted">{message}</p>
      </div>
    </div>
  )
}

function PublicAlreadySubmitted({ surveyTitle }: { surveyTitle: string }) {
  return (
    <div className="min-h-screen bg-bg flex items-center justify-center p-8">
      <div className="bg-surface border border-border rounded-lg shadow-sm p-8 max-w-md w-full text-center">
        <div className="w-12 h-12 mx-auto mb-4 rounded-full bg-success-muted flex items-center justify-center">
          <svg
            className="w-6 h-6 text-success"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M5 13l4 4L19 7"
            />
          </svg>
        </div>
        <h1 className="text-xl font-bold tracking-snug text-fg mb-2">{surveyTitle}</h1>
        <p className="text-fg-muted">
          You&apos;ve already submitted this survey. Thank you for your participation.
        </p>
      </div>
    </div>
  )
}
